<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accessory' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Borrower Name' => '',
    'Buy Date' => '',
    'Categories' => '',
    'Category' => 'カテゴリー',
    'Category ID' => '',
    'Code' => '',
    'Create Category' => '',
    'Create Employee' => '',
    'Create Equipment' => '',
    'Create Lending History' => '',
    'Create System User' => '',
    'Data Status' => '',
    'Delete' => '',
    'Email' => 'Eメール',
    'Employee' => '社員',
    'Employee ID' => '',
    'Employee No' => '',
    'Employees' => '社員',
    'Equipment' => '設備',
    'Equipment ID' => '',
    'Equipment Status' => '',
    'Equipment management' => '@@設備管理@@',
    'Equipments' => '設備',
    'ID' => '',
    'Lend' => '貸出',
    'Lending Date' => '',
    'Lending Histories' => '',
    'Lending History' => '貸出履歴',
    'Login' => 'ログイン',
    'Logout' => 'ログアウト',
    'Model Number' => '',
    'Name' => '',
    'Password' => 'パスワード',
    'Password Hash' => '',
    'Payment Amount' => '',
    'Privileges' => '権限',
    'Remarks' => '',
    'Reset' => '',
    'Return' => '返却',
    'Return Date' => '',
    'Save' => '',
    'Search' => '',
    'Serial Number' => '',
    'Specification' => '',
    'System Users' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Category: {name}' => '',
    'Update Employee: {name}' => '',
    'Update Equipment: {name}' => '',
    'Update Lending History: {name}' => '',
    'Update System User: {name}' => '',
    'User' => 'ユーザ',
    'Username' => 'ログインID',
    'Working Status' => '',
];
